version: '3.9'

services:
  node:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    command: /bin/bash -c "while sleep 1000; do :; done"
    container_name: front_follow_your_money
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - .:/app:cached
